<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_microsite-category-fields',
		'title' => 'Microsite Category Fields',
		'fields' => array (
			array (
				'key' => 'field_55b91c9e31753',
				'label' => 'Is Microsite',
				'name' => 'is_microsite',
				'type' => 'true_false',
				'instructions' => 'Check to edit as a microsite ',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55b91eb5f3a77',
				'label' => 'Logo',
				'name' => 'logo',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_55b91ee3f3a78',
				'label' => 'Social Share Message',
				'name' => 'social_share_message',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55b934152c066',
				'label' => 'Site Share Buttons',
				'name' => 'site_share_buttons',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_55b9343d2c067',
						'label' => 'Facebook and Twitter Title',
						'name' => 'face_twit_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => 'Wheels Afield Magazine',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55b934642c068',
						'label' => 'Email Subject',
						'name' => 'email_subject',
						'type' => 'text',
						'column_width' => '',
						'default_value' => 'Website I came across',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55b934f32c069',
						'label' => 'Email Message',
						'name' => 'email_message',
						'type' => 'text',
						'column_width' => '',
						'default_value' => 'Check out this website!',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_55b91ccdcde58',
				'label' => 'Hide all "buy mag" options',
				'name' => 'hide_all_buy_mag_options',
				'type' => 'true_false',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_55b91d21cde59',
				'label' => 'Mag is Available in Online Store',
				'name' => 'mag_online_store',
				'type' => 'true_false',
				'instructions' => 'Check if this SIP is available in our online store',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55b91d57cde5b',
				'label' => 'Online Store URL',
				'name' => 'online_store_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91d21cde59',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55b91d84cde5d',
				'label' => 'Digital Edition is Available',
				'name' => 'digital_edition_available',
				'type' => 'true_false',
				'instructions' => 'Check if digital edition of this SIP is available',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'message' => '',
				'default_value' => 1,
			),
			array (
				'key' => 'field_55b91db6cde5f',
				'label' => 'Digital Edition Urls',
				'name' => 'digital_edition_urls',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91d84cde5d',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_55b91ddbcde60',
						'label' => 'iTunes URL',
						'name' => 'itunes_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55b91deacde61',
						'label' => 'Google Play URL',
						'name' => 'google_play_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55b91df5cde62',
						'label' => 'Windows Store URL',
						'name' => 'windows_store_url',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_55b91e5cf3a73',
				'label' => 'End Date for Newsstands',
				'name' => 'end_date_newsstands',
				'type' => 'date_picker',
				'instructions' => 'Date when this SIP will stop to be available on newsstands',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'date_format' => 'yymmdd',
				'display_format' => 'dd/mm/yy',
				'first_day' => 1,
			),
			array (
				'key' => 'field_55b91e86f3a75',
				'label' => 'Message displayed if mag is unavailable in stores',
				'name' => 'message_unavailable',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'This magazine is temporary unavailable',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_55b91ef3f3a79',
				'label' => 'Mag Info',
				'name' => 'mag_info',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_55b91f10f3a7a',
						'label' => 'Mag Cover Image',
						'name' => 'mag_cover_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_55b91f29f3a7b',
						'label' => 'Mag Title',
						'name' => 'mag_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_55b91f3ef3a7c',
						'label' => 'Mag Description',
						'name' => 'mag_description',
						'type' => 'textarea',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'Try to make it not more than 156 chars. Limited to 200 chars',
						'maxlength' => 500,
						'rows' => 3,
						'formatting' => 'html',
					),
				),
				'row_min' => 1,
				'row_limit' => 1,
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_55c8dd48fd47a',
				'label' => 'Buy Mag Footer Message',
				'name' => 'buy_mag_foot_message',
				'type' => 'text',
				'instructions' => 'If magazine is not available in newsstands, write this line. Character limit 29',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91ccdcde58',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'NOW AVAILABLE ONLINE!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 29,
			),
			array (
				'key' => 'field_55b91f75f3a7d',
				'label' => 'Additional Elements',
				'name' => 'additional_elements',
				'type' => 'checkbox',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'choices' => array (
					'sponsors_disclaimer' => 'Header Sponsors Disclaimer',
					'second_test_element' => 'Second Test Element',
					'third_test_element' => 'Third Test Element',
				),
				'default_value' => '',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_55b91fc5f3a7e',
				'label' => 'Sponsors Disclaimer Text and Link',
				'name' => 'sponsors_disclaimer',
				'type' => 'textarea',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_55b91c9e31753',
							'operator' => '==',
							'value' => '1',
						),
						array (
							'field' => 'field_55b91f75f3a7d',
							'operator' => '==',
							'value' => 'sponsors_disclaimer',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'BROUGHT TO YOU BY VISTA OUTDOOR INC. AND ITS FAMILY OF <a href="http://www.vistaoutdoor.com/brands/" target="_blank">BRANDS</a>',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 2,
				'formatting' => 'html',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>
