var map_config = {
	'default':{
		'bordercolor':'#ddd', //inter-state borders
		'lakescolor':'#66CCFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'namescolor':'#666666', //color of the abbreviations 
		'namesShadowColor':'#666666', //tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'url':'/forecasts/ALABAMA-deer-hunting-forecast-2016/', //Goto URL
		'target':'_blank', //open link in new window:_blank, open in current window:_self
		'upcolor':'#EBECED', //state's color when page loads
		'overcolor':'#FF6600', //state's color when mouse hover
		'downcolor':'#993366',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'url':'/forecasts/ALASKA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',
		'url':'/forecasts/rocky-mountain-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'url':'/forecasts/ARKANSAS-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'url':'/forecasts/CALIFORNIA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'url':'/forecasts/rocky-mountain-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'url':'/forecasts/DELAWARE-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'url':'/forecasts/FLORIDA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'url':'/forecasts/GEORGIA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'url':'/forecasts/HAWAII-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'url':'/forecasts/IDAHO-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'url':'/forecasts/ILLINOIS-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'url':'/forecasts/INDIANA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'url':'/forecasts/IOWA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'url':'/forecasts/great-plains-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'url':'/forecasts/KENTUCKY-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'url':'/forecasts/LOUISIANA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'url':'/forecasts/MARYLAND-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'url':'/forecasts/MICHIGAN-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'url':'/forecasts/MINNESOTA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'url':'/forecasts/MISSISSIPPI-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'url':'/forecasts/MISSOURI-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'url':'/forecasts/MONTANA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'url':'/forecasts/great-plains-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'url':'/forecasts/NEVADA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'url':'/forecasts/NEW-JERSEY-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'url':'/forecasts/rocky-mountain-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'url':'/forecasts/NEW-YORK-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'url':'/forecasts/NORTH-CAROLINA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'url':'/forecasts/great-plains-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'url':'/forecasts/OHIO-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'url':'/forecasts/OKLAHOMA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'url':'/forecasts/washington-oregon-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'url':'/forecasts/PENNSYLVANIA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'url':'/forecasts/SOUTH-CAROLINA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'url':'/forecasts/great-plains-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'url':'/forecasts/TENNESSEE-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'url':'/forecasts/TEXAS-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'url':'/forecasts/UTAH-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT',
		'url':'/forecasts/new-england-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'url':'/forecasts/VIRGINIA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'url':'/forecasts/washington-oregon-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',
		'url':'/forecasts/WEST-VIRGINIA-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'url':'/forecasts/WISCONSIN-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'url':'/forecasts/rocky-mountain-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'WASHINGTON DC',
		'url':'/forecasts/dc-deer-hunting-forecast-2016/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#0000FF',
		'downcolor':'#993366',
		'enable':false,
	},
}


var map_config_2013 = {
	'default':{
		'bordercolor':'#9CA8B6', //inter-state borders
		'lakescolor':'#66CCFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'namescolor':'#666666', //color of the abbreviations 
		'namesShadowColor':'#666666', //tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'url':'/forecasts/ALABAMA-forecasts-2013/', //Goto URL
		'target':'_blank', //open link in new window:_blank, open in current window:_self
		'upcolor':'#EBECED', //state's color when page loads
		'overcolor':'#FF6600', //state's color when mouse hover
		'downcolor':'#993366',//state's color when mouse clicking
		'enable':true,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'url':'/forecasts/ALASKA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',
		'url':'/forecasts/rocky-mountain-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'url':'/forecasts/ARKANSAS-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'url':'/forecasts/CALIFORNIA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'url':'/forecasts/rocky-mountain-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'url':'/forecasts/DELAWARE-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'url':'/forecasts/FLORIDA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'url':'/forecasts/GEORGIA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'url':'/forecasts/HAWAII-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'url':'/forecasts/IDAHO-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'url':'/forecasts/ILLINOIS-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'url':'/forecasts/INDIANA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'url':'/forecasts/IOWA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'url':'/forecasts/great-plains-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'url':'/forecasts/KENTUCKY-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'url':'/forecasts/LOUISIANA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'url':'/forecasts/MARYLAND-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'url':'/forecasts/MICHIGAN-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'url':'/forecasts/MINNESOTA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'url':'/forecasts/MISSISSIPPI-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'url':'/forecasts/MISSOURI-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'url':'/forecasts/MONTANA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'url':'/forecasts/great-plains-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'url':'/forecasts/NEVADA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'url':'/forecasts/NEW-JERSEY-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'url':'/forecasts/rocky-mountain-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'url':'/forecasts/NEW-YORK-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'url':'/forecasts/NORTH-CAROLINA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'url':'/forecasts/great-plains-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'url':'/forecasts/OHIO-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'url':'/forecasts/OKLAHOMA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'url':'/forecasts/washington-oregon-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'url':'/forecasts/PENNSYLVANIA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'url':'/forecasts/SOUTH-CAROLINA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'url':'/forecasts/great-plains-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'url':'/forecasts/TENNESSEE-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'url':'/forecasts/TEXAS-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'url':'/forecasts/UTAH-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT',
		'url':'/forecasts/new-england-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'url':'/forecasts/VIRGINIA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'url':'/forecasts/washington-oregon-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',
		'url':'/forecasts/WEST-VIRGINIA-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'url':'/forecasts/WISCONSIN-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#EBECED',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':true,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'url':'/forecasts/rocky-mountain-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#FF6600',
		'downcolor':'#993366',
		'enable':false,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'WASHINGTON DC',
		'url':'/forecasts/dc-forecasts-2013/',
		'target':'_blank',
		'upcolor':'#ccc',
		'overcolor':'#0000FF',
		'downcolor':'#993366',
		'enable':false,
	},
}



