<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-and-cat-options',
		'title' => 'Home and Cat Options',
		'fields' => array (
			array (
				'key' => 'field_581b4d950a4b2',
				'label' => 'Home BTF Sections',
				'name' => 'home_btf_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_581b4e100a4b3',
						'label' => 'SECTION',
						'name' => 'home_section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'feat_cat' => 'Featured Category',
							'tv_section' => 'TV Section',
							'sip_section' => 'SIP Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'future_feature_1' => 'Future Feature 1',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_581b51b2784e0',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'instructions' => 'Include store widget?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_581b5243784e1',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'taxonomy',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'feat_cat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'taxonomy' => 'category',
						'field_type' => 'select',
						'allow_null' => 0,
						'load_save_terms' => 0,
						'return_format' => 'id',
						'multiple' => 0,
					),
					array (
						'key' => 'field_581b55f6eeaf2',
						'label' => 'Featured Cat Sponsor Logo',
						'name' => 'feat_cat_sponsor_logo',
						'type' => 'image',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'feat_cat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'save_format' => 'url',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_581b544d0e8f3',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'tv_section',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b54ca0e8f4',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54e60e8f5',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54f30e8f6',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'object',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b551f0e8f7',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b55590e8f8',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b56dc28cc5',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'sip_section',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b56f328cc6',
								'label' => 'title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570228cc7',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570b28cc8',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b572528cc9',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b580328cca',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b5876c2d5b',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b5896c2d5c',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b58e379e4c',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_581b5a7a8b6ba',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
