<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_home-options',
		'title' => 'Home Options',
		'fields' => array (
			array (
				'key' => 'field_581b4d950a4b2',
				'label' => 'Home BTF Sections',
				'name' => 'home_btf_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_581b4e100a4b3',
						'label' => 'SECTION',
						'name' => 'section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'featcat' => 'Featured Category',
							'tv' => 'TV Section',
							'sip' => 'SIP Section',
							'upload_photo' => 'Upload Photo Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'future_feature_1' => 'Future Feature 1',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_581b51b2784e0',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'instructions' => 'Include store widget?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_581b5243784e1',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'featcat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b71ee09604',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_5821f614125c1',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b720e09605',
								'label' => 'Sponsor Logo',
								'name' => 'sponsor_logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b724209606',
								'label' => 'Sponsor Text',
								'name' => 'sponsor_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'Presented by:',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b725f09607',
								'label' => 'Sponsor URL',
								'name' => 'sponsor_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b544d0e8f3',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'tv',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b54ca0e8f4',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54e60e8f5',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54f30e8f6',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b551f0e8f7',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b55590e8f8',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58237c5faac21',
								'label' => 'Video ID',
								'name' => 'video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b56dc28cc5',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'sip',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b56f328cc6',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570228cc7',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bdba3c94d7',
								'label' => 'SIP link text',
								'name' => 'sip_link_text',
								'type' => 'text',
								'instructions' => 'Link to this category or microsite if applicable',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bdbc1c94d8',
								'label' => 'SIP link url',
								'name' => 'sip_link_url',
								'type' => 'text',
								'instructions' => 'Link to this category or microsite if applicable',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570b28cc8',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581bd61fe291f',
								'label' => 'Online Store URL',
								'name' => 'online_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd94156550',
								'label' => 'iTunes URL',
								'name' => 'itunes_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd94956551',
								'label' => 'Google Play URL',
								'name' => 'google_play_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd95556552',
								'label' => 'Windows Store URL',
								'name' => 'windows_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b572528cc9',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b580328cca',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b5876c2d5b',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'instructions' => 'Preferred numbers of chosen categories are 3, 5, 8 or 11',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b5896c2d5c',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b6fa2b321d',
						'label' => 'Upload Photo Section',
						'name' => 'upload_photo',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'upload_photo',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b6ffbb321e',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b7009b321f',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b7019b3220',
								'label' => 'Buttons',
								'name' => 'buttons',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_581b702cb3221',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_581b7069b3222',
										'label' => 'Button URL',
										'name' => 'button_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_581b7078b3223',
								'label' => 'Links',
								'name' => 'links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_581b7092b3224',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_581b70a1b3225',
										'label' => 'Link URL',
										'name' => 'link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_581b70aeb3226',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b70d1b3227',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b58e379e4c',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_581b5a7a8b6ba',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}


// CATEGORY OPTIONS
//------------------------------------------//
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_category-options',
		'title' => 'Category Options',
		'fields' => array (
			array (
				'key' => 'field_582b5cb530ffc',
				'label' => 'Category BTF Sections',
				'name' => 'cat_btf_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_582b5cce30ffd',
						'label' => 'SECTION',
						'name' => 'section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'featcat' => 'Featured Category',
							'tv' => 'TV Section',
							'sip' => 'SIP Section',
							'upload_photo' => 'Upload Photo Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'future_feature_1' => 'Future Feature 1',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_582b5ced30ffe',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'instructions' => 'Include store widget?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_582b5d23ac56c',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'featcat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5d3bac56d',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_582b5d5aac56e',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5d69ac56f',
								'label' => 'Sponsor Logo',
								'name' => 'sponsor_logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5d7bac570',
								'label' => 'Sponsor Text',
								'name' => 'sponsor_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'Sponsored By:',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5d85ac571',
								'label' => 'Sponsor URL',
								'name' => 'sponsor_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5da284c47',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'tv',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5dbb84c48',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5dc384c49',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5dc984c4a',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5dda84c4b',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5de484c4c',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5deb84c4d',
								'label' => 'Video ID',
								'name' => 'video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5e0b90455',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'sip',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5e1e90456',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e2490457',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e3190458',
								'label' => 'SIP link text',
								'name' => 'sip_link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e3b90459',
								'label' => 'SIP link url',
								'name' => 'sip_link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e4a9045a',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5e559045b',
								'label' => 'Online Store URL',
								'name' => 'online_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e679045c',
								'label' => 'iTunes URL',
								'name' => 'itunes_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e699045d',
								'label' => 'Google Play URL',
								'name' => 'google_play_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e789045e',
								'label' => 'Windows Store URL',
								'name' => 'windows_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e819045f',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e8c90460',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5ec73f9e2',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'instructions' => 'Preferred numbers of chosen categories are 3, 5, 8 or 11',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5ee23f9e3',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5f063f9e4',
						'label' => 'Upload Photo Section',
						'name' => 'upload_photo',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'upload_photo',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5f393f9e5',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f403f9e6',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f493f9e7',
								'label' => 'Buttons',
								'name' => 'buttons',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_582b5f573f9e8',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_582b5f623f9e9',
										'label' => 'Button URL',
										'name' => 'button_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_582b5f6c3f9ea',
								'label' => 'Links',
								'name' => 'links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_582b5f7f3f9eb',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_582b5f863f9ec',
										'label' => 'Link URL',
										'name' => 'link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_582b5f903f9ed',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f9e3f9ee',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5fcad28ea',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_582b600cd28eb',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

