<?php

if(function_exists("register_field_group"))
{

	register_field_group(array (
		'id' => 'acf_category-options',
		'title' => 'Category Options',
		'fields' => array (
			array (
				'key' => 'field_582b5cb530ffc',
				'label' => 'Category BTF Sections',
				'name' => 'cat_btf_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_582b5cce30ffd',
						'label' => 'SECTION',
						'name' => 'section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'featcat' => 'Featured Category',
							'tv' => 'TV Section',
							'sip' => 'SIP Section',
							'upload_photo' => 'Upload Photo Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'future_feature_1' => 'Future Feature 1',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_582b5ced30ffe',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'instructions' => 'Include store widget?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_582b5d23ac56c',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'featcat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5d3bac56d',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_582b5d5aac56e',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5d69ac56f',
								'label' => 'Sponsor Logo',
								'name' => 'sponsor_logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5d7bac570',
								'label' => 'Sponsor Text',
								'name' => 'sponsor_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'Sponsored By:',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5d85ac571',
								'label' => 'Sponsor URL',
								'name' => 'sponsor_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5da284c47',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'tv',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5dbb84c48',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5dc384c49',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5dc984c4a',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5dda84c4b',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5de484c4c',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5deb84c4d',
								'label' => 'Video ID',
								'name' => 'video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5e0b90455',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'sip',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5e1e90456',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e2490457',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e3190458',
								'label' => 'SIP link text',
								'name' => 'sip_link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e3b90459',
								'label' => 'SIP link url',
								'name' => 'sip_link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e4a9045a',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_582b5e559045b',
								'label' => 'Online Store URL',
								'name' => 'online_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e679045c',
								'label' => 'iTunes URL',
								'name' => 'itunes_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e699045d',
								'label' => 'Google Play URL',
								'name' => 'google_play_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e789045e',
								'label' => 'Windows Store URL',
								'name' => 'windows_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e819045f',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5e8c90460',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5ec73f9e2',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'instructions' => 'Preferred numbers of chosen categories are 3, 5, 8 or 11',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5ee23f9e3',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5f063f9e4',
						'label' => 'Upload Photo Section',
						'name' => 'upload_photo',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'upload_photo',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_582b5f393f9e5',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f403f9e6',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f493f9e7',
								'label' => 'Buttons',
								'name' => 'buttons',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_582b5f573f9e8',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_582b5f623f9e9',
										'label' => 'Button URL',
										'name' => 'button_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_582b5f6c3f9ea',
								'label' => 'Links',
								'name' => 'links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_582b5f7f3f9eb',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_582b5f863f9ec',
										'label' => 'Link URL',
										'name' => 'link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_582b5f903f9ed',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_582b5f9e3f9ee',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_582b5fcad28ea',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_582b600cd28eb',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_582b5cce30ffd',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_home-options',
		'title' => 'Home Options',
		'fields' => array (
			array (
				'key' => 'field_581b4d950a4b2',
				'label' => 'Home BTF Sections',
				'name' => 'home_btf_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_581b4e100a4b3',
						'label' => 'SECTION',
						'name' => 'section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'featcat' => 'Featured Category',
							'tv' => 'TV Section',
							'sip' => 'SIP Section',
							'upload_photo' => 'Upload Photo Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'future_feature_1' => 'Future Feature 1',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_581b51b2784e0',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'instructions' => 'Include store widget?',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_581b5243784e1',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'featcat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b71ee09604',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_5821f614125c1',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b720e09605',
								'label' => 'Sponsor Logo',
								'name' => 'sponsor_logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b724209606',
								'label' => 'Sponsor Text',
								'name' => 'sponsor_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => 'Presented by:',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b725f09607',
								'label' => 'Sponsor URL',
								'name' => 'sponsor_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b544d0e8f3',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'tv',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b54ca0e8f4',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54e60e8f5',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b54f30e8f6',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581b551f0e8f7',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b55590e8f8',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58237c5faac21',
								'label' => 'Video ID',
								'name' => 'video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b56dc28cc5',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'sip',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b56f328cc6',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570228cc7',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bdba3c94d7',
								'label' => 'SIP link text',
								'name' => 'sip_link_text',
								'type' => 'text',
								'instructions' => 'Link to this category or microsite if applicable',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bdbc1c94d8',
								'label' => 'SIP link url',
								'name' => 'sip_link_url',
								'type' => 'text',
								'instructions' => 'Link to this category or microsite if applicable',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b570b28cc8',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_581bd61fe291f',
								'label' => 'Online Store URL',
								'name' => 'online_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd94156550',
								'label' => 'iTunes URL',
								'name' => 'itunes_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd94956551',
								'label' => 'Google Play URL',
								'name' => 'google_play_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581bd95556552',
								'label' => 'Windows Store URL',
								'name' => 'windows_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b572528cc9',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b580328cca',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b5876c2d5b',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'instructions' => 'Preferred numbers of chosen categories are 3, 5, 8 or 11',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b5896c2d5c',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b6fa2b321d',
						'label' => 'Upload Photo Section',
						'name' => 'upload_photo',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'upload_photo',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_581b6ffbb321e',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b7009b321f',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b7019b3220',
								'label' => 'Buttons',
								'name' => 'buttons',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_581b702cb3221',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_581b7069b3222',
										'label' => 'Button URL',
										'name' => 'button_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_581b7078b3223',
								'label' => 'Links',
								'name' => 'links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_581b7092b3224',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_581b70a1b3225',
										'label' => 'Link URL',
										'name' => 'link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_581b70aeb3226',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_581b70d1b3227',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_581b58e379e4c',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_581b5a7a8b6ba',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_581b4e100a4b3',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_single-category-options',
		'title' => 'Single Category Options',
		'fields' => array (
			array (
				'key' => 'field_584037ec22d3f',
				'label' => 'Category BTF Sections',
				'name' => 'custom_cat_btf_sections',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_584032adfcb6a',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'sub_fields' => array (
					array (
						'key' => 'field_58403d268db0a',
						'label' => 'SECTION',
						'name' => 'section',
						'type' => 'select',
						'column_width' => '',
						'choices' => array (
							'subscribe' => 'Subscribe & Store',
							'featcat' => 'Featured Category',
							'tv' => 'TV Section',
							'sip' => 'SIP Section',
							'upload_photo' => 'Upload Photo Section',
							'explore' => 'Explore Section',
							'wysiwyg' => 'WYSIWYG Editor',
							'custom_html' => 'Custom HTML',
							'multi_video' => 'Multiple Video Section',
							'future_feature_2' => 'Future Feature 2',
							'future_feature_3' => 'Future Feature 3',
						),
						'default_value' => '',
						'allow_null' => 1,
						'multiple' => 0,
					),
					array (
						'key' => 'field_58403d4bf7afb',
						'label' => 'Store',
						'name' => 'store',
						'type' => 'checkbox',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'subscribe',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'choices' => array (
							'store' => 'Store',
						),
						'default_value' => '',
						'layout' => 'vertical',
					),
					array (
						'key' => 'field_58403d75f7afc',
						'label' => 'Featured Category',
						'name' => 'featured_cat',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'featcat',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_58403d87f7afd',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
							array (
								'key' => 'field_58403da3f7afe',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403dbdf7aff',
								'label' => 'Sponsor Logo',
								'name' => 'sponsor_logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_58403de8f7b00',
								'label' => 'Sponsor Text',
								'name' => 'sponsor_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403dedf7b01',
								'label' => 'Sponsor URL',
								'name' => 'sponsor_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_58403e0db64da',
						'label' => 'TV Section',
						'name' => 'tv_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'tv',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_58403e17b64db',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403e1db64dc',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403e27b64dd',
								'label' => 'Logo',
								'name' => 'logo',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_58403e37b64de',
								'label' => 'Link Text',
								'name' => 'link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403e4bb64df',
								'label' => 'Link URL',
								'name' => 'link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403e54b64e0',
								'label' => 'Video ID',
								'name' => 'video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_58403e62b64e1',
						'label' => 'SIP Section',
						'name' => 'sip_section',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'sip',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_58403ea0b64e2',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403eacb64e3',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403eb4b64e4',
								'label' => 'SIP link text',
								'name' => 'sip_link_text',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403ec0b64e5',
								'label' => 'SIP link url',
								'name' => 'sip_link_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403ecab64e6',
								'label' => 'Mag Cover',
								'name' => 'mag_cover',
								'type' => 'image',
								'column_width' => '',
								'save_format' => 'url',
								'preview_size' => 'thumbnail',
								'library' => 'all',
							),
							array (
								'key' => 'field_58403ee1b64e7',
								'label' => 'Online Store URL',
								'name' => 'online_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403eefb64e8',
								'label' => 'iTunes URL',
								'name' => 'itunes_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403efdb64e9',
								'label' => 'Google Play URL',
								'name' => 'google_play_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403f0ab64ea',
								'label' => 'Windows Store URL',
								'name' => 'windows_store_url',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403f0eb64eb',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403f22b64ec',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_58403f4e7579b',
						'label' => 'Explore Section',
						'name' => 'explore_section',
						'type' => 'repeater',
						'instructions' => 'Preferred numbers of chosen categories are 3, 5, 8 or 11',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'explore',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_58403fa17579c',
								'label' => 'Category',
								'name' => 'category',
								'type' => 'taxonomy',
								'column_width' => '',
								'taxonomy' => 'category',
								'field_type' => 'select',
								'allow_null' => 0,
								'load_save_terms' => 0,
								'return_format' => 'id',
								'multiple' => 0,
							),
						),
						'row_min' => '',
						'row_limit' => '',
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_58403fd07579d',
						'label' => 'Upload Photo Section',
						'name' => 'upload_photo',
						'type' => 'repeater',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'upload_photo',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_58403fee7579e',
								'label' => 'Title',
								'name' => 'title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403ff67579f',
								'label' => 'Subtitle',
								'name' => 'subtitle',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_58403ffe757a0',
								'label' => 'Buttons',
								'name' => 'buttons',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_58404016757a1',
										'label' => 'Button Text',
										'name' => 'button_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_5840401c757a2',
										'label' => 'Button URL',
										'name' => 'button_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_58404029757a3',
								'label' => 'Links',
								'name' => 'links',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_5840403c757a4',
										'label' => 'Link Text',
										'name' => 'link_text',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_58404045757a5',
										'label' => 'Link URL',
										'name' => 'link_url',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
								),
								'row_min' => '',
								'row_limit' => '',
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
							array (
								'key' => 'field_5840404e757a6',
								'label' => 'Post ID #1',
								'name' => 'post_id_1',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_5840405e757a7',
								'label' => 'Post ID #2',
								'name' => 'post_id_2',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'row',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_585d45e5a2a8a',
						'label' => 'Multiple Video Section',
						'name' => 'multi_video',
						'type' => 'repeater',
						'column_width' => '',
						'sub_fields' => array (
							array (
								'key' => 'field_585d461fa2a8b',
								'label' => 'Section Title',
								'name' => 'section_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_585d465ca2a8c',
								'label' => 'Featured Video ID',
								'name' => 'featured_video_id',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_585d467ca2a8d',
								'label' => 'Featured Video Title',
								'name' => 'featured_video_title',
								'type' => 'text',
								'column_width' => '',
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'formatting' => 'html',
								'maxlength' => '',
							),
							array (
								'key' => 'field_585d4689a2a8e',
								'label' => 'Video List',
								'name' => 'video_list',
								'type' => 'repeater',
								'column_width' => '',
								'sub_fields' => array (
									array (
										'key' => 'field_585d469fa2a8f',
										'label' => 'Video ID',
										'name' => 'video_id',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_585d46c1a2a90',
										'label' => 'Video Title',
										'name' => 'video_title',
										'type' => 'text',
										'column_width' => '',
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'formatting' => 'html',
										'maxlength' => '',
									),
									array (
										'key' => 'field_585d46cda2a91',
										'label' => 'Video Image',
										'name' => 'video_image',
										'type' => 'image',
										'column_width' => '',
										'save_format' => 'url',
										'preview_size' => 'thumbnail',
										'library' => 'all',
									),
								),
								'row_min' => 0,
								'row_limit' => 0,
								'layout' => 'table',
								'button_label' => 'Add Row',
							),
						),
						'row_min' => 1,
						'row_limit' => 1,
						'layout' => 'table',
						'button_label' => 'Add Row',
					),
					array (
						'key' => 'field_584040b4e89cc',
						'label' => 'WYSIWYG Editor',
						'name' => 'wysiwyg_editor',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'wysiwyg',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_584040d4e89cd',
						'label' => 'Custom HTML',
						'name' => 'custom_html',
						'type' => 'textarea',
						'instructions' => 'Use this field to insert custom html',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_58403d268db0a',
									'operator' => '==',
									'value' => 'custom_html',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => 12,
						'formatting' => 'html',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Section',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));

	register_field_group(array (
		'id' => 'acf_footer-featured-content',
		'title' => 'Footer Featured Content',
		'fields' => array (
			array (
				'key' => 'field_573a2ca08df2a',
				'label' => 'Footer Featured Post or Page',
				'name' => 'footer_post_or_page',
				'type' => 'relationship',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'id',
				'post_type' => array (
					0 => 'all',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => 1,
			),
			array (
				'key' => 'field_574470b4c56ce',
				'label' => 'Custom Image and Url?',
				'name' => 'is_custom_img_and_url',
				'type' => 'true_false',
				'instructions' => 'Check this box to input your own featured image, title, link and call to action.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5744759608d14',
				'label' => 'Featured Content TITLE',
				'name' => 'foot_post_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574471a31c73a',
				'label' => 'Featured Content URL',
				'name' => 'foot_post_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574471441c739',
				'label' => 'Featured Content IMAGE',
				'name' => 'foot_post_img',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'object',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_574471ec1c73b',
				'label' => 'Featured Content CTA',
				'name' => 'foot_post_btn_txt',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'Explore Now!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => -20,
	));
	
/*
	register_field_group(array (
		'id' => 'acf_homepage-fields',
		'title' => 'Homepage Fields',
		'fields' => array (
			array (
				'key' => 'field_573c885547f34',
				'label' => 'Homepage Featured Category',
				'name' => 'homepage_featured_category',
				'type' => 'taxonomy',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57597848699dd',
				'label' => 'Homepage "explore" categories',
				'name' => 'home_explore_categories',
				'type' => 'repeater',
				'instructions' => 'Preferred numbers of chosen categories	are 3, 5, 8 or 11',
				'sub_fields' => array (
					array (
						'key' => 'field_575978cffc7b2',
						'label' => 'Explore Category',
						'name' => 'explore_category',
						'type' => 'taxonomy',
						'column_width' => '',
						'taxonomy' => 'category',
						'field_type' => 'select',
						'allow_null' => 0,
						'load_save_terms' => 0,
						'return_format' => 'id',
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
*/
	
	//Byline
	register_field_group(array (
		'id' => 'acf_byline-field',
		'title' => 'Byline Field',
		'fields' => array (
			array (
				'key' => 'field_578fa885cb826',
				'label' => 'Byline',
				'name' => 'byline',
				'type' => 'text',
				'instructions' => 'Enter the byline',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	
	
	register_field_group(array (
		'id' => 'acf_homepage-options',
		'title' => 'Homepage Options',
		'fields' => array (
			array (
				'key' => 'field_5396f72a968le',
				'label' => 'Homepage Featured Stories.',
				'name' => 'homepage_featured_stories_',
				'type' => 'relationship',
				'instructions' => 'Choose 5 featured posts to be displayed at the beginning of the homepage',
				'return_format' => 'object',
				'post_type' => array (
					0 => 'post',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => 6,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 31,
	));
}

?>
