<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_footer-featured-content',
		'title' => 'Footer Featured Content',
		'fields' => array (
			array (
				'key' => 'field_573a2ca08df2a',
				'label' => 'Footer Featured Post or Page',
				'name' => 'footer_post_or_page',
				'type' => 'relationship',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '!=',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'return_format' => 'id',
				'post_type' => array (
					0 => 'all',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'filters' => array (
					0 => 'search',
					1 => 'post_type',
				),
				'result_elements' => array (
					0 => 'featured_image',
					1 => 'post_type',
					2 => 'post_title',
				),
				'max' => 1,
			),
			array (
				'key' => 'field_574470b4c56ce',
				'label' => 'Custom Image and Url?',
				'name' => 'is_custom_img_and_url',
				'type' => 'true_false',
				'instructions' => 'Check this box to input your own featured image, title, link and call to action.',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_5744759608d14',
				'label' => 'Featured Content TITLE',
				'name' => 'foot_post_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574471a31c73a',
				'label' => 'Featured Content URL',
				'name' => 'foot_post_url',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'none',
				'maxlength' => '',
			),
			array (
				'key' => 'field_574471441c739',
				'label' => 'Featured Content IMAGE',
				'name' => 'foot_post_img',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'save_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
			),
			array (
				'key' => 'field_574471ec1c73b',
				'label' => 'Featured Content CTA',
				'name' => 'foot_post_btn_txt',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_574470b4c56ce',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 'Explore Now!',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => -20,
	));
	register_field_group(array (
		'id' => 'acf_content-elements-position',
		'title' => 'Content Elements Position',
		'fields' => array (
			array (
				'key' => 'field_575acf433b803',
				'label' => 'Sponsored Element',
				'name' => 'sponsored_el',
				'type' => 'select',
				'choices' => array (
					-12 => '-12',
					-11 => '-11',
					-10 => '-10',
					-9 => '-9',
					-8 => '-8',
					-7 => '-7',
					-6 => '-6',
					-5 => '-5',
					-4 => '-4',
					-3 => '-3',
					-2 => '-2',
					-1 => '-1',
					0 => 0,
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					999 => 'Remove this element',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_575ad0576583e',
				'label' => 'Video Element',
				'name' => 'video_el',
				'type' => 'select',
				'choices' => array (
					-12 => '-12',
					-11 => '-11',
					-10 => '-10',
					-9 => '-9',
					-8 => '-8',
					-7 => '-7',
					-6 => '-6',
					-5 => '-5',
					-4 => '-4',
					-3 => '-3',
					-2 => '-2',
					-1 => '-1',
					0 => 0,
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					999 => 'Remove this element',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_575ad09a6583f',
				'label' => 'Inline Add #1',
				'name' => 'inline_ad_1',
				'type' => 'select',
				'choices' => array (
					-12 => '-12',
					-11 => '-11',
					-10 => '-10',
					-9 => '-9',
					-8 => '-8',
					-7 => '-7',
					-6 => '-6',
					-5 => '-5',
					-4 => '-4',
					-3 => '-3',
					-2 => '-2',
					-1 => '-1',
					0 => 0,
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					999 => 'Remove this element',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_575ad0d665840',
				'label' => 'Inline Add #2',
				'name' => 'inline_ad_2',
				'type' => 'select',
				'choices' => array (
					-12 => '-12',
					-11 => '-11',
					-10 => '-10',
					-9 => '-9',
					-8 => '-8',
					-7 => '-7',
					-6 => '-6',
					-5 => '-5',
					-4 => '-4',
					-3 => '-3',
					-2 => '-2',
					-1 => '-1',
					0 => 0,
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					999 => 'Remove this element',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
			array (
				'key' => 'field_575ad0fc65841',
				'label' => 'Inline Add #3',
				'name' => 'inline_ad_3',
				'type' => 'select',
				'choices' => array (
					-12 => '-12',
					-11 => '-11',
					-10 => '-10',
					-9 => '-9',
					-8 => '-8',
					-7 => '-7',
					-6 => '-6',
					-5 => '-5',
					-4 => '-4',
					-3 => '-3',
					-2 => '-2',
					-1 => '-1',
					0 => 0,
					1 => 1,
					2 => 2,
					3 => 3,
					4 => 4,
					5 => 5,
					6 => 6,
					7 => 7,
					8 => 8,
					9 => 9,
					10 => 10,
					11 => 11,
					12 => 12,
					999 => 'Remove this element',
				),
				'default_value' => '',
				'allow_null' => 1,
				'multiple' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_homepage-fields',
		'title' => 'Homepage Fields',
		'fields' => array (
			array (
				'key' => 'field_573c885547f34',
				'label' => 'Homepage Featured Category',
				'name' => 'homepage_featured_category',
				'type' => 'taxonomy',
				'taxonomy' => 'category',
				'field_type' => 'select',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_57597848699dd',
				'label' => 'Homepage "explore" categories',
				'name' => 'home_explore_categories',
				'type' => 'repeater',
				'instructions' => 'Preferred numbers of chosen categories	are 3, 5, 8 or 11',
				'sub_fields' => array (
					array (
						'key' => 'field_575978cffc7b2',
						'label' => 'Explore Category',
						'name' => 'explore_category',
						'type' => 'taxonomy',
						'column_width' => '',
						'taxonomy' => 'category',
						'field_type' => 'select',
						'allow_null' => 0,
						'load_save_terms' => 0,
						'return_format' => 'id',
						'multiple' => 0,
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-fields',
		'title' => 'Post Fields',
		'fields' => array (
			array (
				'key' => 'field_5759cc4ccb5b7',
				'label' => 'Author Name',
				'name' => 'author_name',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5759cbcdb11c6',
				'label' => 'Author Title',
				'name' => 'author_title',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => 'Editor, Gun Dog',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => 38,
			),
			array (
				'key' => 'field_575acc107fc18',
				'label' => 'Hide Date',
				'name' => 'hide_date',
				'type' => 'true_false',
				'message' => '',
				'default_value' => 0,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	
	//Byline
	register_field_group(array (
		'id' => 'acf_byline-field',
		'title' => 'Byline Field',
		'fields' => array (
			array (
				'key' => 'field_578fa885cb826',
				'label' => 'Byline',
				'name' => 'byline',
				'type' => 'text',
				'instructions' => 'Enter the byline',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}

?>
