<?php
//Show Pages
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_show-page-home',
		'title' => 'Show Page Home',
		'fields' => array (
			array (
				'key' => 'field_53ceb4a4f00ca',
				'label' => 'TV Page',
				'name' => 'tv_page',
				'type' => 'true_false',
				'instructions' => 'Check to edit as a TV show page',
				'message' => '',
				'default_value' => 0,
			),
			array (
				'key' => 'field_53cd5aadfceb8',
				'label' => 'Show Menu',
				'name' => 'show_menu',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Assign the show navigation',
				'sub_fields' => array (
					array (
						'key' => 'field_53cd5ad1fceb9',
						'label' => 'Name',
						'name' => 'name',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ceb4a4f00ca',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'Home',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53cd5ae5fceba',
						'label' => 'URL',
						'name' => 'url',
						'type' => 'text',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_53ceb4a4f00ca',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '/tv/about',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53cd59621035f',
				'label' => 'Background Skin',
				'name' => 'background_skin',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Show\'s background image',
				'column_width' => '',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53cd59621035k',
				'label' => 'Background Skin Mobile',
				'name' => 'background_skin_mobile',
				'type' => 'image',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Show\'s background image mobile',
				'column_width' => '',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_53cd598f10360',
				'label' => 'Show Logo',
				'name' => 'show_logo',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'the url of the show logo image',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd5a876d31a',
				'label' => 'Show Title',
				'name' => 'show_title',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Choose if you want a title next to the logo',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd5a876d31b',
				'label' => 'Store URL',
				'name' => 'show_store',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Link to the store',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),		
			array (
				'key' => 'field_53cd5b42ce9ee',
				'label' => 'When to Watch',
				'name' => 'when_to_watch',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Use the show ID to link the when to watch schedule',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd5b61ce9ef',
				'label' => 'Remind Me',
				'name' => 'remind_me',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'The Remind me to watch url',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd6197d13df',
				'label' => 'Facebook',
				'name' => 'facebook',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'facebook page url',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd61e9d13e0',
				'label' => 'Twitter',
				'name' => 'twitter',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Twitter follow link',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd6204d13e1',
				'label' => 'Google',
				'name' => 'google',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'Google Plus link',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_53cd623df2156',
				'label' => 'Shares',
				'name' => 'shares',
				'type' => 'text',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'instructions' => 'link to share count',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_54297167d11cb',
				'label' => 'Seasons',
				'name' => 'seasons',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),

				'instructions' => 'List which seasons to display in the season filter. Please list them from newest to oldest.',
				'sub_fields' => array (
					array (
						'key' => 'field_542972383f704',
						'label' => 'Season',
						'name' => 'season',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'Season 8',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53ff6b8b9f459',
				'label' => 'Category Filter',
				'name' => 'category_filter',
				'type' => 'taxonomy',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),

				'instructions' => 'Choose the categories to filter by.',
				'taxonomy' => 'category',
				'field_type' => 'checkbox',
				'allow_null' => 0,
				'load_save_terms' => 0,
				'return_format' => 'id',
				'multiple' => 0,
			),
			array (
				'key' => 'field_53f4b2515ed4c',
				'label' => 'Sponsors',
				'name' => 'sponsors',
				'type' => 'repeater',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_53ceb4a4f00ca',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),

				'instructions' => 'Add sponsor images.',
				'sub_fields' => array (
					array (
						'key' => 'field_53f4b2725ed4d',
						'label' => 'Sponsor Name',
						'name' => 'name',
						'type' => 'text',
						'instructions' => 'Name of the sponsor.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53f4b2845ed4e',
						'label' => 'Sponsor Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => 'Sponsor Image.',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_53f4b2a75ed4f',
						'label' => 'Sponsor URL',
						'name' => 'url',
						'type' => 'text',
						'instructions' => 'Sponsor link.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'ef_taxonomy',
					'operator' => '==',
					'value' => 'category',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_post-format-galleries',
		'title' => 'Post Format: Galleries',
		'fields' => array (
			array (
				'key' => 'field_53e90c18b4eae',
				'label' => 'Gallery Images',
				'name' => 'gallery_images',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53e90c43b4eaf',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'object',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'instructions' => 'Select an image',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e90c63b4eb0',
						'label' => 'title',
						'name' => 'title',
						'type' => 'text',
						'instructions' => 'Image Title',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53e90c6eb4eb1',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'text',
						'instructions' => 'Image description',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
